"""Key passages of leading cases (candidate excerpts). Used ONLY if found verbatim in the opinion text (usf_build.verify)."""
CANON = {
 "530 U.S. 57": ["The liberty interest at issue in this case—the interest of parents in the care, custody, and control of their children—is perhaps the oldest of the fundamental liberty interests recognized by this Court."],
 "455 U.S. 745": ["Before a State may sever completely and irrevocably the rights of parents in their natural child, due process requires that the State support its allegations by at least clear and convincing evidence."],
 "405 U.S. 645": ["The private interest here, that of a man in the children he has sired and raised, undeniably warrants deference and, absent a powerful countervailing interest, protection."],
 "463 U.S. 248": ["When an unwed father demonstrates a full commitment to the responsibilities of parenthood by \"com[ing] forward to participate in the rearing of his child,\" Caban, 441 U.S., at 392, his interest in personal contact with his child acquires substantial protection under the Due Process Clause."],
 "388 U.S. 1": ["The freedom to marry has long been recognized as one of the vital personal rights essential to the orderly pursuit of happiness by free men."],
 "434 U.S. 374": ["the right to marry is of fundamental importance for all individuals"],
 "576 U.S. 644": ["The Court now holds that same-sex couples may exercise the fundamental right to marry."],
 "431 U.S. 494": ["Our decisions establish that the Constitution protects the sanctity of the family precisely because the institution of the family is deeply rooted in this Nation's history and tradition."],
 "436 U.S. 84": ["A father who agrees, in the interests of family harmony and his children's preferences, to allow them to spend more time in California than was required under a separation agreement can hardly be said to have \"purposefully availed himself\" of the \"benefits and protections\" of California's laws."],
 "504 U.S. 689": ["the domestic relations exception encompasses only cases involving the issuance of a divorce, alimony, or child custody decree."],
 "136 U.S. 586": ["The whole subject of the domestic relations of husband and wife, parent and child, belongs to the laws of the States and not to the laws of the United States."],
 "62 U.S. 582": ["We disclaim altogether any jurisdiction in the courts of the United States upon the subject of divorce, or for the allowance of alimony, either as an original proceeding in chancery or as an incident to divorce a vinculo, or to one from bed and board."],
 "544 U.S. 280": ["cases brought by state-court losers complaining of injuries caused by state-court judgments rendered before the district court proceedings commenced and inviting district court review and rejection of those judgments."],
 "442 U.S. 415": ["Family relations are a traditional area of state concern."],
 "571 U.S. 69": ["state criminal prosecutions, civil enforcement proceedings, and civil proceedings involving certain orders that are uniquely in furtherance of the state courts' ability to perform their judicial functions"],
 "589 U.S. 68": ["a child's habitual residence depends on the totality of the circumstances specific to the case"],
 "596 U.S. 666": ["a court is not categorically required to examine all possible ameliorative measures before denying a Hague Convention petition for return of a child to a foreign country once the court has found that return would expose the child to a grave risk of harm."],
 "560 U.S. 1": ["Mr. Abbott's ne exeat right is a right of custody under the Convention."],
 "439 U.S. 572": ["The pertinent questions are whether the right as asserted conflicts with the express terms of federal law and whether its consequences sufficiently injure the objectives of the federal program to require nonrecognition."],
 "466 U.S. 429": ["The Constitution cannot control such prejudices but neither can it tolerate them. Private biases may be outside the reach of the law, but the law cannot, directly or indirectly, give them effect."],
 "401 U.S. 371": ["given the basic position of the marriage relationship in this society's hierarchy of values and the concomitant state monopolization of the means for legally dissolving this relationship, due process does prohibit a State from denying, solely because of inability to pay, access to its courts to individuals who seek judicial dissolution of their marriages."],
 "486 U.S. 456": ["To withstand intermediate scrutiny, a statutory classification must be substantially related to an important governmental objective."],
 "325 U.S. 226": ["Under our system of law, judicial power to grant a divorce—jurisdiction, strictly speaking—is founded on domicil."],
 "334 U.S. 541": ["The result in this situation is to make the divorce divisible—to give effect to the Nevada decree insofar as it affects marital status and to make it ineffective on the issue of alimony."],
 "354 U.S. 416": ["Since the wife was not subject to its jurisdiction, the Nevada divorce court had no power to extinguish any right which she had under the law of New York to financial support from her husband."],
 "268 U.S. 510": ["The child is not the mere creature of the State; those who nurture him and direct his destiny have the right, coupled with the high duty, to recognize and prepare him for additional obligations."],
 "321 U.S. 158": ["It is cardinal with us that the custody, care and nurture of the child reside first in the parents, whose primary function and freedom include preparation for obligations the state can neither supply nor hinder."],
 "490 U.S. 581": ["the Former Spouses' Protection Act does not grant state courts the power to treat as property divisible upon divorce military retirement pay that has been waived to receive veterans' disability benefits."],
 "564 U.S. 431": ["the Due Process Clause does not automatically require the provision of counsel at civil contempt proceedings to an indigent individual who is subject to a child support order, even if that individual faces incarceration (for up to a year)."],
 "263 U.S. 413": ["If the constitutional questions stated in the bill actually arose in the cause, it was the province and duty of the state court to decide them"],
}
